# Generated by Django 4.2.7 on 2023-11-27 00:48

import comics.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='Número do capítulo')),
                ('link', models.URLField(verbose_name='Link do capítulo')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nome da Obra')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gêneros')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da obra')),
                ('banner', models.URLField(blank=True, null=True, verbose_name='Link imagem banner')),
                ('link', models.URLField(verbose_name='Link da página da obra')),
                ('catalog', models.PositiveIntegerField(blank=True, choices=[(comics.models.TypeCatalog['ASURA'], 'Asura')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField(verbose_name='Imagem da página')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comics.chapter', verbose_name='Capitulo')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comics.comic', verbose_name='Obra'),
        ),
    ]
